const PROFILE_IMAGES = "assets/profiles";
const PROFILE_IMAGES_STATIC = `/${PROFILE_IMAGES}`;
const PROFILE_IMAGES_PATH = `./${PROFILE_IMAGES}`;
const PROJECTS_IMAGES = "assets/projects";
const PROJECTS_IMAGES_STATIC = `/${PROJECTS_IMAGES}`;
const PROJECTS_IMAGES_PATH = `./${PROJECTS_IMAGES}`;

module.exports = {
  PROFILE_IMAGES,
  PROFILE_IMAGES_STATIC,
  PROFILE_IMAGES_PATH,
  PROJECTS_IMAGES,
  PROJECTS_IMAGES_STATIC,
  PROJECTS_IMAGES_PATH,
};
